# playbook.yml

- name: rss_check
  hosts: "*"
  vars:
    rss_feed_url: "{{ rss_feed_url }}"
    rss_keywords: "{{ rss_keywords }}"
    rss_script_location: "{{ rss_script_location }}"
    rss_state_file: "{{ rss_state_file }}"
    discord_webhook_url: "{{ discord_webhook_url }}"

  tasks:
    - name: Check if Python is installed
      command: python3 --version
      register: python_check
      failed_when: python_check.rc != 0
      ignore_errors: false

    - name: Install Python if not present (only applicable for Debian/Ubuntu-based systems)
      apt:
        name: python3
        state: present
      when: python_check is failed

    - name: Ensure pip3 is installed
      apt:
        name: python3-pip
        state: present
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

    - name: Ensure pip3 is installed (for RedHat/CentOS/Fedora)
      yum:
        name: python3-pip
        state: present
      when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Fedora"

    - name: Ensure feedparser module is installed
      pip:
        name: feedparser
        executable: pip3

    - name: Run RSS check script
      command: >
        python3 {{ rss_script_location }} --url={{ rss_feed_url }}
        --keywords="{{ rss_keywords }}"
        --state-file={{ rss_state_file }}
      register: script_output
      ignore_errors: true

    # Comment all lines below if you do not wish to send a Discord webhook
    - name: Send Discrod notification if relevant post found
      uri:
        url: "{{ discord_webhook_url }}" # Required variable
        method: POST
        body_format: json
        body: >-
          {
            "content": "@everyone\n\n🚨💦 A new update related to the Boil Water Advisory was found! Check it out here: {{ script_output.stdout }}"
          }
        headers:
          Content-Type: application/json
        status_code: 204
      when: script_output.rc == 0