# playbook.yml

- hosts: localhost
  tasks:
    - name: Copy RSS check script to target
      copy:
        src: rss_check.py
        dest: /usr/local/bin/rss_check.py
        mode: '0755'

    - name: Ensure Python3 is installed
      package:
        name: python3
        state: present

    - name: Ensure feedparser module is installed
      pip:
        name: feedparser
        executable: pip3

    - name: Set up cron job to check RSS feed every 5 minutes
      cron:
        name: "Check RSS feed for Boil Water Advisory"
        job: "/usr/local/bin/rss_check.py --url={{ rss_feed_url }} --keywords={{ rss_keywords | join(' ') }} && echo 'Boil Water Advisory Update Found' | wall"
        minute: "*/5"

    - name: Ensure the cron service is running
      service:
        name: cron
        state: started
        enabled: yes
