version: '3'

services:
  infrared:
    image: ghcr.io/haveachin/infrared:1.3.3
    container_name: infrared
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "25565:25565/tcp"
    volumes:
      - "./data/configs:/configs"
    expose:
      - "25565"
    environment:
      INFRARED_CONFIG_PATH: "/configs"