version: "3.7"

services:

  influxdb:
    container_name: metrics_influxdb
    image: influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - ./data/influxdb:/var/lib/influxdb2
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.influxdb.rule=Host(`influx.example.com`)"
      - "traefik.http.routers.influxdb.entrypoints=http"
      - "traefik.http.middlewares.influxdb-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.influxdb.middlewares=influxdb-https-redirect"
      - "traefik.http.routers.influxdb-secure.rule=Host(`influx.example.com`)"
      - "traefik.http.routers.influxdb-secure.entrypoints=https"
      - "traefik.http.routers.influxdb-secure.tls=true"
      - "traefik.http.services.influxdb-service.loadbalancer.server.port=8086"

networks:
  proxy:
    external: true