version: '3'

services:
  minecraft:
    container_name: Minecraft
    image: itzg/minecraft-server:java17-jdk
    ports:
      - "25565:25565"
    volumes:
      - ./mc-data:/data
    environment:
      EULA: "TRUE"
    restart: always