# Create tunnel in Cloudflare dashboard
resource "cloudflare_tunnel" "terraform_tunnel" {
  account_id = var.cf_account_id
  name       = var.cf_tunnel_name
  secret     = resource.random_string.cf_generated_secret.result
}

# Build docker-compose.yml into compose_file_contents variable
locals {
  compose_file_contents = <<-EOT
    ## docker-compose.yml
    ## Generated by Terraform
    version: '3.9'

    services:
      cloudflare_tunnel:
        container_name: cloudflaretunnel
        image: cloudflare/cloudflared:latest
        environment:
          - TUNNEL_TOKEN=${cloudflare_tunnel.terraform_tunnel.tunnel_token}
        command: tunnel --no-autoupdate run
  EOT
  compose_file_path = "/home/${var.tunnel_username}/docker-compose.yml"
}